### ISSUE TITLE
Error while trying to download

### ISSUE THREAD

**Issue by Benksy** [dpb587/gget#25]
Hi,
Thank you for this tool. I am trying to download any file with the .ipa extension using gget. It works when I use the example used in the readme but does not work with other repos. I suspect it has to do with the need for authentication using a token for private repos. I tried to add it in the same way **fetch** does, but it didn't work. Below is an example of what I get when I try to run gget:

./gget github.com/jerry977015/Aisa   
gget: error: resolving ref: resolving latest: getting latest release: GET https://api.github.com/repos/jerry977015/Aisa/releases/latest: 404 Not Found []

Thank you for your help!

**Comment by dpb587** [comment]
Hi - using that repo as an example, a few notes...

 * you'll need to specify `--type=blob` to have it look for committed files rather than release assets (its default behavior);
 * you'll also want to be explicit and tell it `@master` since it tries to use the latest official tag release for reference;
 * to glob, you can use either `*.ipa` for the root file or `**/*.ipa` for the nested files (or both)

Something like the following sounds like what you're looking for:

```
$ gget --type=blob --list github.com/jerry977015/Aisa@master '**/*.ipa' '*.ipa'
Found 2 files (28.5M) from github.com/jerry977015/Aisa@master
GoldAsia.ipa
asia_46/jyz_21426_1_1_46.ipa
```

Since it's a public repo you shouldn't need a token aside from potential GitHub throttling, but if you do need to specify one, you can do it through a `GITHUB_TOKEN` environment variable or `~/.netrc` file.

Hope this helps?
