### ISSUE TITLE
[Feature Request] Interactive mode

### ISSUE THREAD

**Issue by graphixillusion** [dpb587/gget#3]
Heya there, i just discovered this project and i like it very much, thank you for the effort. While using it, i was thinking that it would be greate to extend the **"--show-resources"** flag with an interactive mode **--i**. Something like:

`gget github.com/dpb587/gget --show-resources --i`

1. gget-0.2.0-darwin-amd64
2. gget-0.2.0-linux-amd64
3. gget-0.2.0-windows-amd64.exe

What do you want to gget?
Accepted user input: 1,2,3,1-2,*

**Explanation:**

1= download first resource
2= download second resource
3= download third resource
1-2= download 1 AND 2
*= download all

Another small cosmetic suggestion: what about to rename the **--show-resources** to a more easy and fast typing **--list**?

That's it. What do you think about it?

**Comment by dpb587** [comment]
Hello – glad you discovered this project and thanks for your feedback.

re: interactive mode – one of my primary goals is for this tool is automated download workflows, so for that I don't think an interactive mode is needed. Doesn't rule it out, but having implemented interactivity in other projects, I know that adding more of a UI to the CLI can introduce a fair bit more complexity and significantly expands the scope of responsibility (which is the main reason I'd like to avoid adding it). For the time being, I'd prefer for the additional interactivity to be an exercise for the user – something that might be solved with a script or function like below if they really need it.

re: `--list` vs `--show-resources` – I debated this when first implementing and am still on the fence. I went with `--show-*` because I consider it more of a debugging method than a primary use case, so didn't expect it would be used too often and allows consistency with ref vs resources. That being said, I do like easier and faster typing, too. I'll keep thinking about it, and am interested in hearing more about how others are using it, too.

---

```bash
#!/bin/bash

set -euo pipefail

tmpfile="${TMPDIR}/gget-i-${$}"

cleanup() { rm -f "$tmpfile" ; }
trap cleanup EXIT

gget "${1}" --show-resources > "$tmpfile"

awk '{ printf("%d) %s\n", NR, $0) }' < "$tmpfile"
read -p "?) " selections

declare -a files

for selection in $selections ; do
  file="$( sed "${selection}q;d" "$tmpfile" 2>/dev/null )"
  if [[ -z "$file" ]]; then
    echo "invalid selection: $selection"
    exit 1
  fi

  files+=("${file}")
done

exec gget "${@}"  "${files[@]}"
```

**Comment by graphixillusion** [comment]
Thanks for the script: i need to adapt it for Windows cmd.

**Comment by dpb587** [comment]
Closing since built-in interactive mode is currently an anti-goal.

**Comment by dpb587** [comment]
FYI, `--list` has been added in v0.5.0.
