### ISSUE TITLE
Support downloading latest pre-release

### ISSUE THREAD

**Issue by dpb587** [dpb587/gget#5]
Currently, when REF is defaulted, only stable, non-pre-release, non-draft releases can be downloaded. For dev/test/opt-in cases, it'd be helpful to support fetching those assets.

I think pre-releases are currently only a GitHub feature and not supported in GitLab nor BitBucket.

Maybe a flag? Or special ref value? Does specifying pre-release imply *only* pre-release, or in addition to stable? Consider a future feature supporting semver parsing to detect rc/beta/alpha? Some ideas:

```
$ gget github.com/dpb587/gget --latest=stable --latest=pre-release
$ gget github.com/dpb587/gget --latest=any

$ gget github.com/dpb587/gget --stability=any

$ gget github.com/dpb587/gget@latest-pre
$ gget github.com/dpb587/gget@latest-unstable
$ gget github.com/dpb587/gget@latest-any

$ gget github.com/dpb587/gget --allow-pre-release
$ gget github.com/dpb587/gget --include-pre-release
$ gget github.com/dpb587/gget --github-pre-release
```

**Comment by dpb587** [comment]
cc @whalehub

**Comment by ghost** [comment]
@dpb587 I'm going to go into some detail to explain the context for my use case for this feature. The internal logic of my script `ginstall.sh` initially looked something like this to allow a user to install either a specific or the latest version of an application:

```bash
VERSION_PREFIX_V="@v"
VERSION_PREFIX_NONE="@"

INSTALL_DIR_APP=/usr/local/bin

APP_NAME="$2"
APP_VERSION="$3"

if [ "$3" == "latest" ]; then
  VERSION_PREFIX_V=""
  VERSION_PREFIX_NONE=""
  APP_VERSION=""
fi

case in "$2" in
  "docker-compose")
    gget --stdout "${!REPO}""${VERSION_PREFIX_NONE}""${APP_VERSION}" 'docker-compose-Linux-x86_64' > "${INSTALL_DIR_APP:?}"/"${APP_NAME}" && \
    chmod +x "${INSTALL_DIR_APP:?}"/"${APP_NAME}"
  ;;

  "ffsend")
    gget --stdout "${!REPO}""${VERSION_PREFIX_V}""${APP_VERSION}" 'ffsend-v*-linux-x64-static' > "${INSTALL_DIR_APP:?}"/"${APP_NAME}" && \
    chmod +x "${INSTALL_DIR_APP:?}"/"${APP_NAME}"
  ;;
esac
```
**Example #­1:** docker-compose
```bash
whalehub@pdh:~# ginstall.sh docker-compose latest
```
turns into
```bash
gget --stdout github.com/docker/compose 'docker-compose-Linux-x86_64' > /usr/local/bin/docker-compose && \
chmod +x /usr/local/bin/docker-compose 
```

**Example #­2:** ffsend
```bash
whalehub@pdh:~# ginstall.sh ffsend 0.2.64
```
turns into
```bash
gget --stdout github.com/timvisee/ffsend@v0.2.64 'ffsend-v*-linux-x64-static' > /usr/local/bin/ffsend && \
chmod +x /usr/local/bin/ffsend
```

This worked well for almost every application, but as I started adding support for more applications, more and more cases would pop up that required the version number to be reused later on in the script for the installation to succeed.

**Example**: delta
```bash
  "delta")
    gget --stdout "${!REPO}""${VERSION_PREFIX_NONE}""${APP_VERSION}" 'delta-*-x86_64-unknown-linux-gnu.tar.gz' > /tmp/ginstall.tar.gz && \
    tar -xf /tmp/ginstall.tar.gz -C "${INSTALL_DIR_APP:?}" delta-"${APP_VERSION}"-x86_64-unknown-linux-gnu/"${APP_NAME}" --strip-components=1 && \
    chmod +x "${INSTALL_DIR_APP:?}"/"${APP_NAME}" && \
    rm "${TMP_DIR_TAR_GZ}"
  ;;
```

Here, the command

```bash
whalehub@pdh:~# ginstall.sh delta latest
```

 turns into

```bash
gget --stdout github.com/dandavison/delta 'delta-*-x86_64-unknown-linux-gnu.tar.gz' > /tmp/ginstall.tar.gz && \
tar -xf /tmp/ginstall.tar.gz -C /usr/local/bin delta-latest-x86_64-unknown-linux-gnu/delta --strip-components=1 && \
chmod +x /usr/local/bin/delta && \
rm /tmp/ginstall.tar.gz
```

which, of course, results in the following error message since no developer names every new release asset "latest":

```bash
√ delta-0.1.1-x86_64-unknown-linux-gnu.tar.gz done
tar: delta-latest-x86_64-unknown-linux-gnu/delta: Not found in archive
tar: Exiting with failure status due to previous errors
```

I solved this issue by always first piping the output from `gget --show-ref` through `sed` and then reusing the resulting version number as the `APP_VERSION` variable, regardless of whether the user is installing a specific or the latest version of an application.

**Example:** delta

```bash
APP_VERSION="$(gget --show-ref "${!REPO}" | sed '2d;s|tag[[:blank:]]||g;s|v||g')"
```

That little `sed` construction turns

```bash
whalehub@pdh:~# gget --show-ref github.com/dandavison/delta
tag     0.1.1
commit  9732c888eea48038f4d34d67a80999907a04ee50
```

into

```bash
whalehub@pdh:~# gget --show-ref github.com/dandavison/delta | sed '2d;s|tag[[:blank:]]||g;s|v||g'
0.1.1
```

This allows all of those corner cases to work perfectly.

Now, while this more sophisticated solution works for ~98% of the apps I've added (over 200 in total by now), there are some rare cases where using `latest` as the version argument fails because the entire release history consists exclusively of pre-releases.

There are currently five such applications supported by my tool: [Age](https://github.com/FiloSottile/age/releases), [Golty](https://github.com/XiovV/Golty/releases), [Intercert](https://github.com/evenh/intercert/releases), [Louketo Proxy](https://github.com/louketo/louketo-proxy/releases) and [Rage](https://github.com/str4d/rage/releases).

In these cases, `gget` will currently exit with an error since it can't find a `latest` tag to use. I'm currently supporting those applications with a rather ugly hack:

```bash
if [ "$3" == "latest" ]; then
  case "$2" in
    "age")
      APP_VERSION="1.0.0-beta2"
    ;;

    "go-auto-yt")
      APP_VERSION="0.5.1"
    ;;

    "intercert")
      APP_VERSION="0.0.2"
    ;;

    "louketo-proxy")
       APP_VERSION="1.0.0-alpha.1"
    ;;

    "rage")
      APP_VERSION="0.4.0"
    ;;
esac
fi
```

My preferred solution for this problem would be a flag for `gget` that I can add to the installation command of every application, one that allows `gget` to seamlessly fall back to querying the latest pre-release tag of a repository when the user has not specified a version number and the repository has no `latest` release tag for it to use.

Something like

```bash
$ gget github.com/dpb587/gget --allow-pre-release-fallback
```

I think for the other use case where a user explicitly wants to get the latest tag, regardless of whether or not it's a `latest` or pre-release tag, this flag you listed would be ideal

```bash
$ gget github.com/dpb587/gget --include-pre-release
```

I think those two flags would cover all the common use cases.

**Comment by whalehub** [comment]
@dpb587 This is unrelated to this issue, but I realized three things after rereading the README for `gget` just now.

1.) I should stop using the  `--stdout` flag iny my script since this code

```bash
gget --stdout github.com/timvisee/ffsend@v0.2.64 'ffsend-v*-linux-x64-static' > /usr/local/bin/ffsend && \
chmod +x /usr/local/bin/ffsend
```

```bash
gget --stdout github.com/dandavison/delta 'delta-*-x86_64-unknown-linux-gnu.tar.gz' > /tmp/ginstall.tar.gz
```

can be expressed more elegantly and concisely like this:

```bash
gget --executable github.com/timvisee/ffsend@v0.2.64 /usr/local/bin/ffsend='ffsend-v*-linux-x64-static'
```
```bash
gget github.com/dandavison/delta /tmp/ginstall.tar.gz='delta-*-x86_64-unknown-linux-gnu.tar.gz'
```

2.) I can make use of the  `--exclude` flag to consolidate most of the pattern matches into a few broad ones without resulting in overlapping matches.

3.) I can pipe the output from `--show-resources` through `sed` just like `--show-ref` and use the result as a useful variable later in the script.

These things will allow me to massively reduce the size of my script, probably by more than 50%. 😄

**Comment by whalehub** [comment]
This is unrelated to this issue, but I realized three things after rereading the README for `gget` just now.

1.) I should stop using the  `--stdout` flag in my script since this code

```bash
gget --stdout github.com/timvisee/ffsend@v0.2.64 'ffsend-v*-linux-x64-static' > /usr/local/bin/ffsend && \
chmod +x /usr/local/bin/ffsend
```

```bash
gget --stdout github.com/dandavison/delta 'delta-*-x86_64-unknown-linux-gnu.tar.gz' > /tmp/ginstall.tar.gz
```

can be expressed more elegantly and concisely like this:

```bash
gget --executable github.com/timvisee/ffsend@v0.2.64 /usr/local/bin/ffsend='ffsend-v*-linux-x64-static'
```
```bash
gget github.com/dandavison/delta /tmp/ginstall.tar.gz='delta-*-x86_64-unknown-linux-gnu.tar.gz'
```

2.) I can make use of the  `--exclude` flag to consolidate most of the pattern matches into a few broad ones without resulting in overlapping matches.

3.) I can pipe the output from `--show-resources` through `sed` just like `--show-ref` and use the result as a useful variable later in the script.

These things will allow me to massively reduce the size of my script, probably by more than 50%. 😄

**Comment by dpb587** [comment]
Thanks for the details and example repositories. I've been giving it some thought and added an initial implementation this evening to the branch (though I think it needs more thought on UX).

It introduces a `--ref-stability=` option where `stable`, `pre-release`, or `any` can be specified (with `stable` being the existing behavior and default). I think I prefer a single option rather than separate `--allow-pre-release-fallback`/`--include-pre-release`-type flags because it's more declarative about what the user considers acceptable. Example usage looks like:

```
$ go run . github.com/str4d/rage '*darwin*' --ref-stability=pre-release
Downloading 1 file (2M) from github.com/str4d/rage@v0.4.0
√ rage-v0.4.0-x86_64-darwin.tar.gz done
```

Admittedly, it doesn't directly solve the `--allow-pre-release-fallback` case. I see the use case, but I have mixed feelings about the user not knowing whether they're getting "stable" or pre-release. If they don't care, they can just ask for `any` stability. But if they do want fallback, it suggests they're okay with pre-releases today, and I'm not sure why they'd be uncomfortable with a later pre-release after a stable release. Especially if they're not caring about version locking to begin with.

I'm not quite satisfied with the `--ref-stability` option name yet, so might change that before release. I am looking for a way to group related options around how the "latest" ref gets resolved. For example, I've also added a `--ref-version=` option to support version constraint-based selection as well. Example usage looks like:

```
$ go run . github.com/whalehub/ginstall.sh --ref-version=2.6.x --type=blob ginstall.sh
Downloading 1 file (47.9K) from github.com/whalehub/ginstall.sh@v2.6.1
√ ginstall.sh done
```

If you have thoughts on the new, tentative options or want to do more convincing of the fallback case, I'm happy to hear.

**Comment by ghost** [comment]
@dpb587 Thanks! I managed to implement my own fallback solution using only the new `--ref-stability` flag, so I don't think there needs to be a dedicated flag in `gget` for this use case after all.

**Old Version Check**
```bash
        *)
          REPO="$(echo "REPO_${2^^}" | sed 's/[-.]/_/g;s/+/_PLUS/g')"
          CHECK_RESULT="$(gget --show-ref "${!REPO}" 2>/dev/null | sed '2d;s|tag[[:blank:]]||g;s|v||g')"
          if [ -z "${CHECK_RESULT}" ]; then
            echo -e "${UNSUPPORTED_APP}\n${USAGE_INFORMATION}"
            exit 1
          else
            echo -e "The latest version of $2 is v${CHECK_RESULT}."
            exit 0
          fi
        ;;
```

**New Version Check**
```bash
        *)
          REPO="$(echo "REPO_${2^^}" | sed 's/[-.]/_/g;s/+/_PLUS/g')"
          if [ -z "${!REPO}" ]; then
            echo -e "${UNSUPPORTED_APP}\n${USAGE_INFORMATION}"
            exit 1
          fi

          VERSION_CHECK="$(gget --ref-stability=stable --show-ref "${!REPO}" 2>/dev/null | sed '2d;s|tag[[:blank:]]||g;s|v||g')"
          if [ -z "${VERSION_CHECK}" ]; then
            APP_VERSION="$(gget --ref-stability=pre-release --show-ref "${!REPO}" 2>/dev/null | sed '2d;s|tag[[:blank:]]||g;s|v||g')"
          else
            APP_VERSION="${VERSION_CHECK}"
          fi
          echo -e "The latest version of $2 is v${APP_VERSION}."
          exit 0
        ;;
```

Here are some examples:

**Syncthing** (latest: v1.6.1, pre: v1.7.0-rc.1)
```bash
whalehub@pdh:~# ginstall.sh -c syncthing
The latest version of syncthing is v1.6.1.
```

**Age** (latest: none, pre: v1.0.0-beta2)
```bash
whalehub@pdh:~# ginstall.sh -c age
The latest version of age is v1.0.0-beta2.
```

**Non-Existent App**
```bash
whalehub@pdh:~# ginstall.sh -c asjlfasashs
Error: This application is not supported by ginstall.sh.
Please run "ginstall.sh --help" for usage information.
```

**Comment by dpb587** [comment]
The fallback approach looks good to me. I'd suggest removing the `--ref-stability=stable` part since it's the default.

I'm going to stick with the `--ref-` prefix for now, and I'll cut a release soon after a bit more testing of the current changes.
